[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"

[workspace]
members = [
	# Libs
	"crates/libs/lib-core",
	"crates/libs/lib-io",

	# Services
	"crates/services/dispatcher",
	"crates/services/builder",

	# Tools 
	"crates/tools/ejcli",
]
resolver = "2"
