[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"

[workspace]
members = [
	# Libs
	"crates/libs/lib-core",
	"crates/libs/lib-io",
	"crates/libs/lib-requests",

	# Services
	"crates/services/ejdispatcher",
	"crates/services/ejbuilder",
	"crates/services/ejcli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["André Costa andre_miguel_costa@hotmail.com"]
edition = "2024"
