# Build Configuration File
# This file defines boards and their configurations for building and running jobs

# Global settings
[global]
version = "1.0.0"


# Boards
[[boards]]
name = "Raspberry Pi 3"
description = "Raspberry Pi 3 Model B+"

[[boards.configs]]
name = "Rpi3 Wayland"
tags = ["wayland", "arm64"]
# Path to build and run scripts, you can either have one script per board config or you can
#  use the arguments passed to the script to know which action to take, arguments are as follows:
# argv[1] is the action the runner should take should be either `build` or `run`
# argv[2] is the config (.toml) path
# argv[3] is the board name
# argv[4] is the board config name
# argv[5] is the path to the socket so that he can establish a socket connection with ejb
build_script = "/home/work/rpi/wayland/scripts/build_rpi4_wayland.sh"
run_script = "/home/work/rpi/wayland/scripts/run_rpi4_wayland.sh"
results_path = "/home/work/rpi/wayland/results/results.json"
library_path = "/home/work/rpi/wayland/lib"

[[boards.configs]]
name = "Rpi3 SDL"
tags = ["sdl2", "arm64"]
build_script = "/home/work/rpi/sdl/scripts/build_rpi4_wayland.sh"
run_script = "/home/work/rpi/sdl/scripts/run_rpi4_wayland.sh"
results_path = "/home/work/rpi/sdl/results/results.json"
library_path = "/home/work/rpi/sdl/lib"

[[boards]]
name = "x86 PC running Fedora 41"
description = "AMD Ryzen 5 3600 desktop with NVIDIA GTX 1650"

[[boards.configs]]
name = "Wayland build for desktop"
tags = ["wayland", "x86_64"]
build_script = "/home/work/x86/wayland/scripts/build_rpi4_wayland.sh"
run_script = "/home/work/x86/wayland/scripts/run_rpi4_wayland.sh"
results_path = "/home/work/x86/wayland/results/results.json"
library_path = "/home/work/x86/wayland/lib"

[[boards.configs]]
name = "X11 build for desktop"
tags = ["x11", "x86_64"]
build_script = "/home/work/x86/x11/scripts/build_rpi4_wayland.sh"
run_script = "/home/work/x86/x11/scripts/run_rpi4_wayland.sh"
results_path = "/home/work/x86/x11/results/results.json"
library_path = "/home/work/x86/x11/lib"
