name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: |
        docker compose up -d
        export $(cat ./dev-config/dev.env | xargs) 
        sleep 3
        cargo run &
        sleep 1 # give the app enough time to start
        cargo test --verbose --test '*'

